# Assignment 3


# Task 1:

# 1

In [ ]:
#Write a function to compute 5/0 and use try/except to catch the exceptions.


In [1]:
try:
    a=0
    b=5/a
    print(" The code is fine and executed")
except:
    print("There is an issue with code")


There is an issue with code


# 2

In [ ]:
"""Implement a Python program to generate all sentences where subject is in ["Americans",
"Indians"] and verb is in ["Play", "watch"] and the object is in ["Baseball","cricket"].
Hint: Subject,Verb and Object should be declared in the program as shown below.
subjects=["Americans ","Indians"]
verbs=["play","watch"]
objects=["Baseball","Cricket"]
Output should come as below:
Americans play Baseball.
Americans play Cricket.
Americans watch Baseball.
Americans watch Cricket.
Indians play Baseball.
Indians play Cricket.
Indians watch Baseball.
Indians watch Cricket."""




In [4]:
subjects=["Americans ","Indians"]
verbs=["play","watch"]
objects=["Baseball","Cricket"]

for i in subjects:
    for j in verbs:
        for k in objects:
            print(i+" "+j+" "+k)
            

Americans  play Baseball
Americans  play Cricket
Americans  watch Baseball
Americans  watch Cricket
Indians play Baseball
Indians play Cricket
Indians watch Baseball
Indians watch Cricket


# Task 2:

# 1.

In [ ]:
"""
Write a function so that the columns of the output matrix are powers of the input vector.
The order of the powers is determined by the increasing boolean argument. Specifically, when
increasing is False, the i-th output column is the input vector raised element-wise to the power
of N - i - 1.
HINT: Such a matrix with a geometric progression in each row is named for AlexandreTheophile Vandermonde.
NOTE: The solution shared through Github should contain the source code used and the
screenshot of the output.
"""

In [8]:
import numpy as np   
def vander(col, n, inc):
    
    if not inc:
        temp = np.array([x**(n-1-i) for x in col for i in range(n)])
        temp=temp.reshape(matrix.size,n)
    elif inc:
        temp = np.array([x**i for x in col for i in range(n)])
        temp=temp.reshape(matrix.size,n)
    
    return temp

matrix = np.array([1,2,3,4,5])
no_col =len(matrix)
Dec_order = vander(matrix,no_col,False)
Inc_order = vander(matrix,no_col,True)

print(Dec_order)

print("\n")

print(Inc_order)



[[  1   1   1   1   1]
 [ 16   8   4   2   1]
 [ 81  27   9   3   1]
 [256  64  16   4   1]
 [625 125  25   5   1]]


[[  1   1   1   1   1]
 [  1   2   4   8  16]
 [  1   3   9  27  81]
 [  1   4  16  64 256]
 [  1   5  25 125 625]]
